### ISSUE TITLE
Orderby Notworking ! 

### ISSUE THREAD

**Issue by rajkuttie** [wilmoore/orderby-time.js#1]
I have collection of json data. I try to order by all data based on date. 
My date format is  ex : 2017/05/19 17:10:00 . But I can't . Documentation gives   this date format 2015-10-20T06:01:47.427Z.

**Comment by wilmoore** [comment]
Hi @rajkuttie,

I can probably help you out; however, I'll need the following:

1. Code/data you want to sort
2. What is the expected result
3. What is the result you are getting

**Comment by wilmoore** [comment]
You need to pass an `ISO 8601` formatted date/time string, otherwise, `new Date` will give evaluate the date as something unexpected. You can format your incoming date with your favorite date manipulation library before passing to `orderby-time`.
